title: Mrunal Pallempati
description: a tiny website about mrunal pallempati.
baseurl: 
url: https://mrunaaaal.github.io

#theme: hacked-jekyll

exclude:
  - LICENSE
  - README.md
  - vendor/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  